version: '3.1'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    restart: always
    volumes:
      - ./docker/config:/etc/mysql/conf.d
    ports:
      - 3306:3306
