version: '3.1'

services:

  mongodb:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_DATABASE=portfolio
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=pass
    ports:
      - 27017:27017
